# Generated by Django 2.2.6 on 2019-12-11 15:21

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191130_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=api.helpers.PathAndRename('images')),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('AP', 'Applicant'), ('EV', 'Evaluator'), ('AD', 'Administrator'), ('NA', 'Not Available')], default='AP', max_length=2),
        ),
    ]
