# Generated by Django 2.2.6 on 2019-12-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191211_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
