# Generated by Django 2.2.6 on 2020-01-08 03:38

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nric_picture',
            field=models.ImageField(null=True, upload_to=api.helpers.PathAndRename('nric')),
        ),
    ]
