# Generated by Django 2.2.6 on 2020-02-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userevent',
            options={'ordering': ['-date_time']},
        ),
    ]
