# Generated by Django 2.2.6 on 2020-02-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200212_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='relationship_type',
            field=models.CharField(choices=[('SL', 'Self'), ('SP', 'Spouse'), ('SB', 'Siblings'), ('PR', 'Parents'), ('CH', 'Children'), ('OT', 'Others')], default='SL', max_length=2),
        ),
    ]
