# Generated by Django 2.2.6 on 2019-12-11 15:21

import api.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20191130_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('EN', 'Energy'), ('WA', 'Water'), ('TR', 'Transportation'), ('BI', 'Biodiversity'), ('WE', 'Waste'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('initiative', models.CharField(default='NA', max_length=100)),
                ('improvement', models.CharField(default='NA', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('rebate_percentage', models.IntegerField(default=0)),
                ('supporting_doc', models.ImageField(null=True, upload_to=api.helpers.PathAndRename('assessment'))),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('evaluation_type', models.CharField(choices=[('EQ', 'Equipment'), ('SY', 'System'), ('EF', 'Efficiency'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('mark', models.IntegerField(default=0)),
                ('comment', models.CharField(default='NA', max_length=100)),
                ('date_evaluated', models.DateField(null=True)),
                ('supporting_doc', models.ImageField(null=True, upload_to=api.helpers.PathAndRename('evaluation'))),
                ('assessment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_assessment_id_evaluation', to='applications.ApplicationAssessment')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEvaluationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('session', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening'), ('NA', 'Not Available')], default='NA', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='evaluator_executed',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
        migrations.AddField(
            model_name='application',
            name='date_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='evaluator_nominated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_nominated_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SN', 'Sent'), ('AV', 'Approved'), ('RJ', 'Rejected'), ('IP', 'In process'), ('EV', 'Evaluated'), ('PD', 'Paid'), ('NA', 'Not Available')], default='SN', max_length=2),
        ),
        migrations.DeleteModel(
            name='ApplicationType',
        ),
        migrations.AddField(
            model_name='applicationevaluationschedule',
            name='application_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_id_evaluation_schedule', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='applicationassessment',
            name='application_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_id_assessment', to='applications.Application'),
        ),
    ]
