# Generated by Django 2.2.6 on 2019-12-13 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20191211_1542'),
        ('applications', '0003_auto_20191211_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_house_id', to='houses.House'),
        ),
    ]
