# Generated by Django 2.2.6 on 2019-12-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_applied_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationassessment',
            name='supporting_doc',
        ),
    ]
