# Generated by Django 2.2.6 on 2019-12-13 21:59

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_applicationassessment_supporting_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationassessment',
            name='supporting_doc',
            field=models.ImageField(null=True, upload_to=api.helpers.PathAndRename('assessment')),
        ),
    ]
