# Generated by Django 2.2.6 on 2019-12-18 03:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicationassessment_supporting_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEvaluationAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('aspect_type', models.CharField(choices=[('EN', 'Energy'), ('WA', 'Water'), ('TR', 'Transportation'), ('BI', 'Biodiversity'), ('WE', 'Waste'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('aspect', models.CharField(default='NA', max_length=100)),
                ('incentive', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicationevaluation',
            name='assessment_id',
        ),
        migrations.RemoveField(
            model_name='applicationevaluation',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='applicationevaluation',
            name='date_evaluated',
        ),
        migrations.RemoveField(
            model_name='applicationevaluation',
            name='evaluation_type',
        ),
        migrations.RemoveField(
            model_name='applicationevaluation',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='applicationevaluation',
            name='supporting_doc',
        ),
        migrations.AddField(
            model_name='applicationevaluation',
            name='efficiency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationevaluation',
            name='equipment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationevaluation',
            name='remarks',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='applicationevaluation',
            name='system',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationevaluation',
            name='evaluation_assessment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_assessment_id_evaluation', to='applications.ApplicationEvaluationAssessment'),
        ),
    ]
