# Generated by Django 2.2.6 on 2019-12-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20191218_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationevaluation',
            name='application_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_id_evaluation', to='applications.Application'),
        ),
    ]
