# Generated by Django 2.2.6 on 2019-12-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_applicationevaluation_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('CM', 'Completed'), ('CR', 'Created'), ('IE', 'In evaluation'), ('IP', 'In profess'), ('NA', 'Not Available'), ('PD', 'Paid'), ('RJ', 'Rejected'), ('SM', 'Submitted')], default='CR', max_length=2),
        ),
    ]
