# Generated by Django 2.2.6 on 2019-12-29 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20191218_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('equipment', models.IntegerField(default=0)),
                ('system', models.IntegerField(default=0)),
                ('efficiency', models.IntegerField(default=0)),
                ('remarks', models.CharField(default='NA', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('session', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening'), ('NA', 'Not Available')], default='NA', max_length=2)),
            ],
        ),
        migrations.RenameModel(
            old_name='ApplicationEvaluationAssessment',
            new_name='AssessmentAspect',
        ),
        migrations.RemoveField(
            model_name='applicationevaluationschedule',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='applicationassessment',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='applicationassessment',
            name='assessment_type',
        ),
        migrations.RemoveField(
            model_name='applicationassessment',
            name='improvement',
        ),
        migrations.RemoveField(
            model_name='applicationassessment',
            name='initiative',
        ),
        migrations.RemoveField(
            model_name='applicationassessment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='applicationassessment',
            name='rebate_percentage',
        ),
        migrations.AddField(
            model_name='applicationassessment',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_assessment_application', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='applicationassessment',
            name='assessment_aspect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_assessment_assessment_aspect', to='applications.AssessmentAspect'),
        ),
        migrations.AddField(
            model_name='applicationassessment',
            name='remarks',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='evaluator_nominated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_evaluator_nominated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ApplicationEvaluation',
        ),
        migrations.DeleteModel(
            name='ApplicationEvaluationSchedule',
        ),
        migrations.AddField(
            model_name='evaluationschedule',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_schedule_application', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='application_assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_application_assessment', to='applications.ApplicationAssessment'),
        ),
    ]
