# Generated by Django 2.2.6 on 2020-02-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_applicationevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.AlterModelOptions(
            name='applicationevent',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterModelOptions(
            name='assessmentaspect',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='evaluationschedule',
            options={'ordering': ['-date']},
        ),
    ]
