# Generated by Django 2.2.6 on 2019-11-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='application_type',
            new_name='assessment_type',
        ),
        migrations.RemoveField(
            model_name='assessmenttype',
            name='name',
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='assessment_group',
            field=models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='max_rebate',
            field=models.IntegerField(default=0),
        ),
    ]
