# Generated by Django 2.2.6 on 2019-11-30 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20191130_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('aspect', models.CharField(default='NA', max_length=100)),
                ('initiative', models.CharField(default='NA', max_length=100)),
                ('improvement', models.CharField(default='NA', max_length=100)),
                ('quantity', models.CharField(default='NA', max_length=100)),
                ('rebate', models.CharField(default='NA', max_length=100)),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.Assessment')),
            ],
        ),
    ]
