# Generated by Django 2.2.6 on 2019-11-30 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='application_type',
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='assessment_tax_account',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='building_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='parmanent_occupant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='stay_duration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='HouseVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('vehicle_type', models.CharField(blank=True, max_length=255)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
        ),
    ]
