# Generated by Django 2.2.6 on 2019-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20191130_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HouseType',
        ),
        migrations.RemoveField(
            model_name='house',
            name='name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='parmanent_occupant',
        ),
        migrations.RemoveField(
            model_name='house',
            name='stay_duration',
        ),
        migrations.AddField(
            model_name='house',
            name='permanent_occupant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='stay_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='vehicle_bicycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='vehicle_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='vehicle_motorcycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='vehicle_other',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='building_type',
            field=models.CharField(choices=[('CD', 'Condominium'), ('FL', 'Flat'), ('TO', 'Townhouse'), ('TE', 'Terrace House'), ('BG', 'Bungalow'), ('SD', 'Semidetached'), ('AP', 'Apartment'), ('SA', 'Service Apartment'), ('OT', 'Other')], default='BG', max_length=2),
        ),
        migrations.DeleteModel(
            name='HouseVehicle',
        ),
    ]
