# Generated by Django 2.2.6 on 2019-12-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20191211_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='stay_from',
            new_name='stay_begin',
        ),
    ]
