# Generated by Django 2.2.6 on 2020-01-15 03:09

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20191217_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='assessment_tax_doc',
            field=models.ImageField(null=True, upload_to=api.helpers.PathAndRename('assessment_tax')),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_bill_1_doc',
            field=models.ImageField(null=True, upload_to=api.helpers.PathAndRename('bills')),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_bill_1_month',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_bill_1_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_bill_2_doc',
            field=models.ImageField(null=True, upload_to=api.helpers.PathAndRename('bills')),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_bill_2_month',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_bill_2_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_bill_3_doc',
            field=models.ImageField(null=True, upload_to=api.helpers.PathAndRename('bills')),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_bill_3_month',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_bill_3_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='water_bill_1_doc',
            field=models.ImageField(null=True, upload_to=api.helpers.PathAndRename('bills')),
        ),
        migrations.AddField(
            model_name='house',
            name='water_bill_1_month',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='water_bill_1_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='water_bill_2_doc',
            field=models.ImageField(null=True, upload_to=api.helpers.PathAndRename('bills')),
        ),
        migrations.AddField(
            model_name='house',
            name='water_bill_2_month',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='water_bill_2_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='water_bill_3_doc',
            field=models.ImageField(null=True, upload_to=api.helpers.PathAndRename('bills')),
        ),
        migrations.AddField(
            model_name='house',
            name='water_bill_3_month',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='water_bill_3_usage',
            field=models.IntegerField(default=0),
        ),
    ]
