# Generated by Django 2.2.6 on 2020-02-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_houseevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houseevent',
            options={'ordering': ['-date_time']},
        ),
    ]
