# Generated by Django 2.2.6 on 2020-02-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_auto_20200217_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='city',
            new_name='area',
        ),
    ]
