# Generated by Django 2.2.6 on 2019-11-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebate',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rebate',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rebate',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
