# Generated by Django 2.2.6 on 2019-12-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20191211_1521'),
        ('rebates', '0002_auto_20191130_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rebate',
            old_name='amount',
            new_name='amount_approved',
        ),
        migrations.RemoveField(
            model_name='rebate',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='rebate',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='rebate',
            name='name',
        ),
        migrations.AddField(
            model_name='rebate',
            name='application_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='rebate',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='RebateType',
        ),
    ]
