# Generated by Django 2.2.6 on 2020-02-06 03:13

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='pdf',
            field=models.FileField(null=True, upload_to=api.helpers.PathAndRename('pdf')),
        ),
    ]
