# Generated by Django 2.2.6 on 2020-02-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200206_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='pdf',
            new_name='pdf_file_url',
        ),
    ]
