# Generated by Django 2.2.6 on 2019-12-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketquestion',
            name='status',
            field=models.CharField(choices=[('RS', 'Resolved'), ('UR', 'Unresolved')], default='UR', max_length=2),
        ),
    ]
