# Generated by Django 2.2.6 on 2019-12-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketquestion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketquestion',
            name='status',
            field=models.CharField(choices=[('RS', 'Resolved'), ('UR', 'Unresolved'), ('OT', 'Other')], default='UR', max_length=2),
        ),
    ]
