# Generated by Django 2.2.6 on 2020-01-15 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_event_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
