# Generated by Django 2.2.6 on 2020-02-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200115_0309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketanswer',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.AlterModelOptions(
            name='ticketevent',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterModelOptions(
            name='ticketquestion',
            options={'ordering': ['-status', '-date_submitted']},
        ),
    ]
